spring.datasource.url=jdbc:postgresql://localhost:5432/atelier
spring.datasource.username=postgres
spring.datasource.password=epilef
spring.datasource.driver-class-name=org.postgresql.Driver

server.address=0.0.0.0
debug=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.h2.console.enabled=false

server.port=8082
server.error.include-message=always

atelier.cors.allowed-origins=http://localhost:3000,http://localhost:4173,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:4173,http://127.0.0.1:5173,http://192.168.0.17:5173