/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTutoriaisRouteImport } from './routes/_authenticated/tutoriais'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedIndividualRouteImport } from './routes/_authenticated/individual'
import { Route as AuthenticatedGrupoRouteImport } from './routes/_authenticated/grupo'
import { Route as AuthenticatedAnotacoesIndividuaisRouteImport } from './routes/_authenticated/anotacoes-individuais'
import { Route as AuthenticatedAnotacoesGeraisRouteImport } from './routes/_authenticated/anotacoes-gerais'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutoriaisRoute = AuthenticatedTutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndividualRoute = AuthenticatedIndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrupoRoute = AuthenticatedGrupoRouteImport.update({
  id: '/grupo',
  path: '/grupo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnotacoesIndividuaisRoute =
  AuthenticatedAnotacoesIndividuaisRouteImport.update({
    id: '/anotacoes-individuais',
    path: '/anotacoes-individuais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnotacoesGeraisRoute =
  AuthenticatedAnotacoesGeraisRouteImport.update({
    id: '/anotacoes-gerais',
    path: '/anotacoes-gerais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/anotacoes-gerais': typeof AuthenticatedAnotacoesGeraisRoute
  '/anotacoes-individuais': typeof AuthenticatedAnotacoesIndividuaisRoute
  '/grupo': typeof AuthenticatedGrupoRoute
  '/individual': typeof AuthenticatedIndividualRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/anotacoes-gerais': typeof AuthenticatedAnotacoesGeraisRoute
  '/anotacoes-individuais': typeof AuthenticatedAnotacoesIndividuaisRoute
  '/grupo': typeof AuthenticatedGrupoRoute
  '/individual': typeof AuthenticatedIndividualRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/anotacoes-gerais': typeof AuthenticatedAnotacoesGeraisRoute
  '/_authenticated/anotacoes-individuais': typeof AuthenticatedAnotacoesIndividuaisRoute
  '/_authenticated/grupo': typeof AuthenticatedGrupoRoute
  '/_authenticated/individual': typeof AuthenticatedIndividualRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/tutoriais': typeof AuthenticatedTutoriaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/anotacoes-gerais'
    | '/anotacoes-individuais'
    | '/grupo'
    | '/individual'
    | '/painel'
    | '/tutoriais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alertas'
    | '/anotacoes-gerais'
    | '/anotacoes-individuais'
    | '/grupo'
    | '/individual'
    | '/painel'
    | '/tutoriais'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alertas'
    | '/_authenticated/anotacoes-gerais'
    | '/_authenticated/anotacoes-individuais'
    | '/_authenticated/grupo'
    | '/_authenticated/individual'
    | '/_authenticated/painel'
    | '/_authenticated/tutoriais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutoriais': {
      id: '/_authenticated/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof AuthenticatedTutoriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/individual': {
      id: '/_authenticated/individual'
      path: '/individual'
      fullPath: '/individual'
      preLoaderRoute: typeof AuthenticatedIndividualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupo': {
      id: '/_authenticated/grupo'
      path: '/grupo'
      fullPath: '/grupo'
      preLoaderRoute: typeof AuthenticatedGrupoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anotacoes-individuais': {
      id: '/_authenticated/anotacoes-individuais'
      path: '/anotacoes-individuais'
      fullPath: '/anotacoes-individuais'
      preLoaderRoute: typeof AuthenticatedAnotacoesIndividuaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anotacoes-gerais': {
      id: '/_authenticated/anotacoes-gerais'
      path: '/anotacoes-gerais'
      fullPath: '/anotacoes-gerais'
      preLoaderRoute: typeof AuthenticatedAnotacoesGeraisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAnotacoesGeraisRoute: typeof AuthenticatedAnotacoesGeraisRoute
  AuthenticatedAnotacoesIndividuaisRoute: typeof AuthenticatedAnotacoesIndividuaisRoute
  AuthenticatedGrupoRoute: typeof AuthenticatedGrupoRoute
  AuthenticatedIndividualRoute: typeof AuthenticatedIndividualRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedTutoriaisRoute: typeof AuthenticatedTutoriaisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAnotacoesGeraisRoute: AuthenticatedAnotacoesGeraisRoute,
  AuthenticatedAnotacoesIndividuaisRoute:
    AuthenticatedAnotacoesIndividuaisRoute,
  AuthenticatedGrupoRoute: AuthenticatedGrupoRoute,
  AuthenticatedIndividualRoute: AuthenticatedIndividualRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedTutoriaisRoute: AuthenticatedTutoriaisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
